exp_name: "'@{dataset.name}'_'@{network.name}'_'@{preprocessor.name}'_'@{trainer.name}'_e'@{optimizer.num_epochs}'_lr'@{optimizer.lr}'_'@{mark}'_w_fea_n_logits_distill_4kl_8fd_0.1cl_0.2dcl_0.0001mi_loss_0.0001ml_0.0001dml_0.01dt-new-submission-mean-plus-plus-theorem2-empirical-noise_on_both_loss-run02/s'@{seed}'"
# "'@{dataset.name}'_'@{network.name}'_'@{trainer.name}'_e'@{optimizer.num_epochs}'_lr'@{optimizer.lr}'_'@{mark}'/s'@{seed}'"
output_dir: ./results/
save_output: True
merge_option: default
mark: default
seed: 0

num_gpus: 1
num_workers: 8
num_machines: 1
machine_rank: 0

preprocessor:
  name: base

network:
  pretrained: True

pipeline:
  name: generative_ood_distill_pipeline

trainer:
  name: generative_ood_distill_trainer

evaluator:
  name: base

optimizer:
  name: sgd
  num_epochs: 200  # 100 500 ## 200 for theoretical guarantee, 100 for normal exps
  lr: 0.005  # 0.005 for r18, 0.005 for r50
  momentum: 0.9
  weight_decay: 0.0005

recorder:
  name: base
  save_all_models: False
